services:
  customergateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__Database=Server=localhost;Port=5432;Database=CustomerDB;User Id=postgres;Password=postgres;Include Error Detail=true
    depends_on:
      - customerdb
    ports:
      - "5000:8080"
      - "5050:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

  customerdb:
    container_name: customerdb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=CustomerDB
    restart: always
    ports:
        - "5432-5432"
    volumes:
      - postgres_customer:/var/lib/postgresql/data/ # where the customer db will reside on disk 

