services:
  customergateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__Database=Server=customerdb;Port=5432;Database=CustomerDB;User Id=postgres;Password=postgres;Include Error Detail=true
    depends_on:
      - customerdb
    ports:
      - "5002:8080"
      - "5052:8081"
      - "5003:8080"
      - "5053:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

  customerdb:
    container_name: customerdb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=CustomerDB
    restart: always
    ports:
        - "5432-5432"
    volumes:
      - postgres_customer:/var/lib/postgresql/data/ # where the customer db will reside on disk 

  discountgateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__Database=Server=discountdb;Port=5432;Database=DiscountDB;User Id=postgres;Password=postgres;Include Error Detail=true
    depends_on:
      - discountdb
    ports:
      - "5000:8080"
      - "5050:8081"
      - "5001:8080"
      - "5051:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

  discountdb:
    container_name: discountdb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=DiscountDB
    restart: always
    ports:
        - "5432-5432"
    volumes:
      - postgres_discount:/var/lib/postgresql/data/ # where the discount db will reside on disk 