services:
  customergateway:
    image: ${DOCKER_REGISTRY-}customergateway
    build:
      context: ..
      dockerfile: src/Services/Customer/Dockerfile

  customerdb:
    image: postgres

  discountgateway:
    image: ${DOCKER_REGISTRY-}discountgateway
    build:
      context: ..
      dockerfile: src/Services/Discount/Dockerfile

  discountdb:
    image: postgres

volumes:
  postgres_customer:
  postgres_discount:



